### ISSUE TITLE
[BUG] unable to utilize Spellbook type Token on Stream Deck, getting TypeError: undefined. spellcastingEntries.forEach is not a function in pf2e.js

### ISSUE THREAD

**Issue by churney-unity** [MaterialFoundry/MaterialDeck#115] opened 2023-11-22 20:08 UTC
**Setup**
 - OS: Windows 11
 - Browser: Chrome
 - Module version: 1.6.2
 - Foundry version: 11.3.15
 - Gaming system & version: PF2E 5.9.4
 - Any other modules enabled: yes

**Describe the bug**
Unable to use Spellbok Mode - I have tried with multiple tokens, including a Bard, as well as Ezren imported from the beginner box from testing, but get the same console errors with both on load, and when clicking on the button on my SD. I am by no means fluent in JS, but I did try saving a copy of pf2e.js and modifying line 468 to `Object.keys(spellcastingEntries).forEach(spellCastingEntry` => { 
however this threw an undefined error on line 470.

**Screenshots**
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/70146538/5828781f-f3e4-427b-9968-58ffb1caafbe)

**Console Log**
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/systems/pf2e.js:468" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">pf2e.js:468</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: undefined. spellcastingEntries.forEach is not a function
[Detected 1 package: MaterialDeck]
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at pf2e.buildSpellData (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/systems/pf2e.js:468:29" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">pf2e.js:468:29</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at pf2e.getSpellData (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/systems/pf2e.js:501:57" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">pf2e.js:501:57</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at pf2e.getSpells (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/systems/pf2e.js:519:30" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">pf2e.js:519:30</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TokenHelper.getSpells (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/systems/tokenHelper.js:398:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">tokenHelper.js:398:28</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TokenControl.pushData (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/actions/token.js:395:41" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">token.js:395:41</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TokenControl.update (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6969/modules/MaterialDeck/src/actions/token.js:18:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">token.js:18:28</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | buildSpellData | @ | pf2e.js:468
-- | -- | -- | --
  | getSpellData | @ | pf2e.js:501
  | getSpells | @ | pf2e.js:519
  | getSpells | @ | tokenHelper.js:398
  | pushData | @ | token.js:395
  | update | @ | token.js:18
  | await in update (async) |   |  
  | (anonymous) | @ | MaterialDeck.js:623
  | #call | @ | foundry.js:730
  | callAll | @ | foundry.js:687
  | _render | @ | foundry.js:5855
  | await in _render (async) |   |  
  | _render | @ | foundry.js:6532
  | (anonymous) | @ | pf2e.mjs:1403
  | maintainFocusInRender | @ | pf2e.mjs:1350
  | _render | @ | pf2e.mjs:1403
  | render | @ | foundry.js:5769
  | render | @ | foundry.js:7111
  | _onClickLeft2 | @ | foundry.js:56272
  | callback | @ | foundry.js:31766
  | #handleClickLeft2 | @ | foundry.js:31971
  | #handleMouseDown | @ | foundry.js:31938
  | notifyListeners | @ | earcut.js:128
  | notifyTarget | @ | earcut.js:128
  | propagate | @ | earcut.js:128
  | dispatchEvent | @ | earcut.js:128
  | mapPointerDown | @ | earcut.js:128
  | mapEvent | @ | earcut.js:128
  | onPointerDown | @ | earcut.js:128

</span></div>
</body>
</html>

**Additional context**

**Comment by MaterialFoundry** [comment] 2023-11-25 00:43
I'm able to reproduce this. It looks like something changed in the pf2e code so it no longer functions properly.
I'll take a look at it for the next update.

**Comment by RHeynsZa** [comment] 2024-01-03 17:37
Bumping this, same issue

**Comment by MaterialFoundry** [comment] 2024-05-09 14:43
This should be fixed in the latest version

**Closed as completed by MaterialFoundry** 2024-05-09 14:43 UTC
Labels: bug
