### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jjf41992** [MaterialFoundry/MaterialDeck#114] opened 2023-10-28 18:25 UTC
**Setup**
 - OS: Windows (Material Companion), Linux Ubuntu 18.04(Foundry Server)
 - Browser: Chrome/Edge
 - Module version: 1.6.2 // SD Plugin 1.6.1
 - Foundry version: v11 BUILD 313
 - Gaming system & version: PF2E 5.7.4
 - Any other modules enabled: [yes/no]

**Describe the bug**
Macroboard macro buttons not working after update to Material Companion update. SD seems to be connected and other functions are working fine.

**Screenshots**
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/72322167/c3dfee8e-9e08-41f6-9988-97c14e5c46c7)
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/72322167/0cd32572-9f9e-4fe5-b394-074d9ab9609f)
![image](https://github.com/MaterialFoundry/MaterialDeck/assets/72322167/db104a99-dcf7-4e2c-9a04-1b3c81cac25f)

**Console Log**
TypeError: Cannot read properties of undefined (reading '2')
    at MacroControl.executeBoard (macro.js:288:51)
    at MacroControl.keyPress (macro.js:240:22)
    at analyzeWSmessage (MaterialDeck.js:202:26)
    at ws.onmessage (MaterialDeck.js:248:9)

**Comment by MaterialFoundry** [comment] 2023-11-14 21:41
I think I know what the problem is. I assume that you haven't created a macro with arguments, right?
If so, could you go into the macro config, for any macro fill in a random value in the arguments field, make sure you click somewhere else, and then clear the macro field again.
See if this fixes it for you.

**Comment by MaterialFoundry** [comment] 2024-05-09 14:43
This should be fixed in the latest version

**Closed as completed by MaterialFoundry** 2024-05-09 14:43 UTC
Labels: bug
